[workspace]
members = [
#   Comment out until crates exist
  "crates/core",
  "crates/data",
  "crates/inference",
#   "crates/exporters/onnx",
#   "crates/exporters/compiled",
   "bindings/python", # PyO3 binding crate (must contain its own Cargo.toml)
]
resolver = "2"
