[package]
name = "forestfire-python"
version = "0.0.0"
edition = "2025"
publish = false

[lib]
name = "forestfire_python"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.25", features = ["extension-module"] }

