name: Python Lint (ruff)

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install uv
        run: |
          python -m pip install --upgrade pip
          pip install uv

      - name: Show versions
        run: |
          python --version
          uvx ruff --version

      - name: Ruff lint
        run: |
          # Emits GitHub-friendly annotations on PRs
          uvx ruff check --output-format=github .

      - name: Ruff formatting (check only)
        run: |
          # Fails if formatting changes would be made
          uvx ruff format --check .
